#!/bin/bash
banner(){
	echo >&2 `tput setaf 3; tput bold;`"+--------------------------------------------+"``
	echo >&2 `tput setaf 3; tput bold;`"+                                            +"``
	echo >&2 `tput setaf 3; tput bold;`"+             `tput setaf 0;tput bold;`BLACKBOx INSTALLER`tput setaf 3;tput bold;`             +"``
	echo >&2 `tput setaf 3; tput bold;`"+                                            +"``
	echo >&2 `tput setaf 3; tput bold;`"+--------------------------------------------+"``

}
blackbox_install(){
	if [ $(whoami) != "root" ];then
		echo "You must be root to run script."
		exit 1337
	fi
	cd ..
	pip2 install -r requirements.txt
	cp -R blackbox/ /opt/
	echo '#!/bin/sh' > /bin/blackbox
	echo 'python2 /opt/blackbox/blackbox.py "$@"' >> /bin/blackbox
	chmod 755 /bin/blackbox;chmod +x /bin/blackbox
	rm -rf blackbox/
	blackbox
	if [ $? -eq 0 ]; then
		echo "WORKED ! NOW YOU CAN USE command! : blackbox"
	else
		echo "ERROR FAIL!"
		exit 1337
	fi
}
banner